version: '3.8'

services:
  postgres:
    container_name: postgresDB
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER:-User}
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: Order
    ports:
      - "127.0.0.1:0:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom-network

  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "127.0.0.1:0:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASSWORD: password
    ports:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - custom-network

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:

networks:
  custom-network:
    driver: bridge



